update pipeline

diff --git a/.github/workflows/deploy-skills.yml b/.github/workflows/deploy-skills.yml
--- a/.github/workflows/deploy-skills.yml
+++ b/.github/workflows/deploy-skills.yml
@@ -38,25 +38,16 @@ jobs:
 
       - name: Check Skill Status
         run: |
-          ask smapi get-skill-status --skill-id ${{ secrets.SKILL_ID }} --resource interactionModel > status.json
-          cat status.json
-
-      # - name: Update
-      #   uses: xavidop/alexa-ask-aws-cli-docker@v1.0.6
-      #   id: update_skills_step
-      #   with:
-      #     command: |
-      #       ask smapi set-interaction-model -s ${{ secrets.SKILL_ID }} -l fr-FR --interaction-model file:libs/lib-common/src/assets/amazon-alexa-skills/skills.json
-      #       ask smapi get-skill-status --skill-id ${{ secrets.SKILL_ID }} --resource interactionModel --profile default > status.json
-      #       cat status.json
-      #       node -e "console.log(require('./status.json').interactionModel['fr-FR'].lastUpdateRequest.status"
-      #   env:
-      #     ASK_ACCESS_TOKEN: ${{ secrets.ASK_ACCESS_TOKEN }}
-      #     ASK_REFRESH_TOKEN: ${{ secrets.ASK_REFRESH_TOKEN }}
-      #     ASK_VENDOR_ID: ${{ secrets.ASK_VENDOR_ID }}
-      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      #     SKILL_ID: ${{ secrets.SKILL_ID }}
-
-      - name: Get the output
-        run: echo "The result was ${{ steps.update_skills_step.outputs.result }}"
+          status="IN_PROGRESS"
+          i=0
+          while [ "$status" = "SUCCEEDED" ]; do
+            status=$(ask smapi get-skill-status --skill-id ${{ secrets.SKILL_ID }} --resource interactionModel)
+            status=$(node $status -e "console.log(process.argv[1].interactionModel['fr-FR'].lastUpdateRequest.status)")
+            sleep 60
+            ((i=i+1))
+            if [ $i -lt 300 ]; then
+              echo "❌ UNABLE TO CHECK THE SUCCESS OF THE DEPLOYMENT ❌"
+              exit 1
+            fi
+          done
+          echo "✅ SUCCESS ✅"
